import moment from 'moment';
import R from 'assets/R';

export default {
  apInvoiceId: 0,
  adOrgId: 1000433,
  adClientId: null,
  createdby: null,
  updated: new Date().getTime(),
  updatedby: null,
  description: '',
  isactive: 'Y',
  isDeleted: null,
  apInvoiceGroupId: null,
  documentNo: null,
  groupChange: null,
  type: '0',
  typeRate: 1,
  template: '',
  symbol: '',
  invoiceNo: '',
  paymentType: '',
  transDate: moment(new Date()).format('DD/MM/YYYY'),
  sellerName: '',
  taxCode: '',
  isTemplate: 'N',
  currencyRate: '',
  requestBeforeTaxAmount: 0,
  requestTaxAmount: 0,
  requestAmount: 0,
  approvedBeforeTaxAmount: 0,
  approvedTaxAmount: 0,
  approvedAmount: 0,
  dueDate: moment(new Date()).format('DD/MM/YYYY'),
  isMap: null,
  clearingAmount: null,
  notRequestAmount: null,
  isSync: null,
  accountingDate: null,
  serviceType: null,
  originalInvoiceId: null,
  filename: null,
  path: null,
  attachedFileId: null,
  cCurrencyName: null,
  attachedTime: null,
  apInvoiceGroupPreId: null,
  isAccountingCost: null,
  isGift: null,
  withholdingTax: null,
  posted: null,
  value: null,
  fwmodelId: 0,
  isSize: true,
  cBpartnerId: null,
  cBpartnerName: '',
  cCurrencyId: '',
  cPeriodId: null,
  cDocumentTypeId: null,
  cApInvoiceId: null,
  cTaxCategoryId: null,
  cPaymentTermId: null,
  cPaymentTermName: '',
  cChannelId: null,
  cLocationId: null,
  cLocationName: '',
  cWorkUnitId: null,
  cWorkUnitName: '',
  cAccountCrId: null,
  cCostCenterId: null,
  paymentMethod: 'UNC',
  cDepartmentId: 1005025,
  address: '',
}
