export const dataDetailedInvoice = {
  adOrgId: null,
  taxCode: '',
  partnerName: '',
  address: '',
  identify: '',
  adOrgName: '',
  approverId: null,
  approverName: null,
  feedback: null,
  description: '',
  docstatus: null,
  cBpartnerId: null,
  cBpartnerName: null,
  isDeleted: null,
  createdby: 21447,
  updatedby: 21447,
  cRequestPartnerId: null,
}
